events {}

http {

    upstream frontend {
        server front:80;
    }

    upstream login {
        server api_login:8000;
    }

    upstream usuarios {
        server api_usuarios:8001;
    }

    server {
        listen 80;
        server_name _;

        # 🔹 API LOGIN
        location /api/login/ {
            proxy_pass http://login/;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 🔹 API USUARIOS
        location /api/usuarios/ {
            proxy_pass http://usuarios/;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 🔹 FRONTEND (SIN try_files)
        location / {
            proxy_pass http://frontend;

            proxy_set_header Host $host;
        }
    }
}